runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

skip_files:
  - .github/
  - .parcel-cache/
  - .assets/
  - .dist/
  - node_modules/
  - src/
